### ISSUE TITLE
Github themes do not box code

### ISSUE THREAD

**Issue by sejgit** [jasonm23/markdown-soma#9]
First, thank you for this package, both my son & I use it often.

This is extremely minor but the GitHub css themes do not 'box' code type as do the soma themes (and would be on the GitHub site).  I tried looking at differences between the soma and GitHub themes to copy but they are written very differently.  Sorry, css is not my forte. Any chances of either an update to the GitHub themes or if you prefer how they are can you send me in the right direction to make my own?

**Comment by jasonm23** [comment]
Hi, thanks @sejgit. I'm glad you are both finding markdown-soma useful.

So this is an example Markdown in the Github dark theme.

<img width="1450" alt="Screenshot 2023-03-29 at 1 17 06 PM" src="https://user-images.githubusercontent.com/71587/228443280-6de51f42-8d78-474b-9117-74796549628c.png">

I am sympathetic to your request, however, reluctant to add a border to the theme.  So as not to disrupt other users who are happy with the theme as is.

Note, it will look like this:

<img width="1450" alt="Screenshot 2023-03-29 at 1 21 14 PM" src="https://user-images.githubusercontent.com/71587/228443976-b7bb72c2-c60a-49c6-8ed7-253dec4b01f6.png">

You could do a couple of things, at this point.  Make your own copies of the github themes, and modify the lines:

https://github.com/jasonm23/markdown-soma/blob/e604b9e4a65bbd2057befbfaebfa73d00bd9826a/styles/github-dark.css#L826-L834

https://github.com/jasonm23/markdown-soma/blob/e604b9e4a65bbd2057befbfaebfa73d00bd9826a/styles/github-light.css#L826-L834


So that these definitions both include a solid border:

For the dark theme, you could use: 

`border: solid #f6f8fa11;`

For the light theme:

`border: solid #161b2211;`

Let me know if this solves the issue for you.

**Comment by sejgit** [comment]
perfect! I appreciate you don't want to mess with what's not broke for the majority.  You taught me how to fish.  I will mess with both border and background-colour and find my zen.  If of value to others I can share back.  On spring break with my kids so likely next week.  Thanks for the advice & your package!
